---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php package for ubuntu server
    apt:
      name: 
        - apache2
        - libapache2-mod-php 
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


  - name: install apache2 and php package for ubuntu CentOS
    yum:    
      name: 
        - httpd
        - php 
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS" 

- hosts: db_servers
  become: true
  tasks:

  - name: install mysql package for CentOS
    yum:
      name: mysql
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mysql package for Ubuntu
    apt:
      name: mysql-server
      state: latest
    when: ansible_distribution == "Ubuntu"
